# Generated by Django 6.1 on 2026-08-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savannah_app', '0004_remove_appointment_unique_doctor_appointment_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_rescheduled',
            field=models.BooleanField(default=True, help_text='True if this appointment was created by rescheduling an older appointment'),
        ),
    ]
