# Generated by Django 6.1 on 2026-08-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Savannah_app', '0005_appointment_is_rescheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinical_services',
        ),
    ]
