# Generated by Django 6.1 on 2026-08-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savannah_app', '0006_remove_appointment_clinical_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_rescheduled',
            field=models.BooleanField(default=False, help_text='True if this appointment was created by rescheduling an older appointment'),
        ),
    ]
