# Generated by Django 6.1 on 2026-08-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savannah_app', '0008_doctorworkinghours_start_before_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='Savannah_app.clinicalservice'),
        ),
    ]
